<?php
require_once(__DIR__.'/inc/enqueue.php');
require_once(__DIR__.'/inc/login.php');
require_once(__DIR__.'/inc/cpt.php');
require_once(__DIR__.'/inc/tax.php');
require_once(__DIR__.'/inc/api.php');
require_once(__DIR__.'/inc/maps.php');
require_once(__DIR__.'/inc/theme_settings.php');
require_once(__DIR__.'/inc/utilities.php');